Re-BOOT Web: db.h File Reference
db.h File Reference
SQLite3 persistence layer — users, jobs, and sessions.
#include <stdint.h>
#include <sqlite3.h>
Classes
struct User
Represents a user account stored in the database.
struct Job
Represents a firmware flash job stored in the database.
Macros
#define DB_STR64 64
#define DB_STR128 128
#define DB_STR256 256
#define DB_STR512 512
Functions
int db_open (const char *path)
Open (and schema-initialise) the SQLite3 database.
void db_close (void)
Close the database connection and release resources.
int db_user_by_username (const char *username, User *out)
Look up a user by username.
int db_user_by_id (int64_t id, User *out)
Look up a user by primary-key ID.
int db_user_create (const char *username, const char *pwhash, const char *role, int64_t *id_out)
Insert a new user row.
int db_user_delete (int64_t id)
Delete a user by ID.
int db_user_list (User **out, int *cnt)
Fetch all users ordered by ID.
int64_t db_job_create (const Job *j)
Insert a new job row.
int db_job_get (int64_t id, Job *out)
Fetch a single job by ID (JOINs user table for username).
int db_job_list (Job **out, int *cnt)
Fetch the most recent 100 jobs, newest first.
int db_job_set_started (int64_t id)
Mark a job as running and record its start timestamp.
int db_job_set_finished (int64_t id, const char *status, int exit_code)
Mark a job as finished, recording final status and exit code.
int db_job_delete (int64_t id)
Delete a job row by ID.
int db_session_create (const char *token, int64_t user_id, int64_t expires_at)
Insert or replace a session record.
int db_session_user (const char *token, int64_t now, int64_t *uid_out)
Validate a session token and retrieve the owning user ID.
int db_session_delete (const char *token)
Delete a session record (logout).
Detailed Description
SQLite3 persistence layer — users, jobs, and sessions.
Thin wrapper around libsqlite3. All operations use prepared statements. The database is opened once at startup (db_open()) and closed at shutdown (db_close()). WAL journal mode is enabled for concurrent read access.
Author
Subhajit Roy subha.nosp@m.jitr.nosp@m.oy005.nosp@m.@gma.nosp@m.il.co.nosp@m.m
Date
2026-05-06
Definition in file db.h.
Function Documentation
db_close()
void db_close (void)
Close the database connection and release resources.
Definition at line 135 of file db.c.
References g_db.
Referenced by main().
db_job_create()
int64_t db_job_create (const Job * j)
Insert a new job row.
Parameters
j Populated Job struct (the id field is ignored).
Returns
New row ID on success, -1 on failure.
Definition at line 278 of file db.c.
References Job::device, Job::extra_args, g_db, Job::hex_file, Job::interface, Job::name, Job::node_id, Job::reset_flag, Job::retries, Job::tcp_port, Job::user_id, and Job::verbose.
Referenced by handle_jobs_create().
db_job_delete()
int db_job_delete (int64_t id)
Delete a job row by ID.
Parameters
id Row ID to delete.
Returns
0 on success, -1 on failure.
Definition at line 401 of file db.c.
References g_db.
Referenced by handle_job_delete().
db_job_get()
int db_job_get (int64_t id, Job * out)
Fetch a single job by ID (JOINs user table for username).
Parameters
id Row ID to search.
out Struct to fill on success.
Returns
0 if found, -1 otherwise.
Definition at line 312 of file db.c.
References fill_job(), g_db, and JOB_SELECT.
Referenced by handle_job_get(), handle_job_status(), and runner_thread().
db_job_list()
int db_job_list (Job ** out, int * cnt)
Fetch the most recent 100 jobs, newest first.
Parameters
out Receives a heap-allocated array; caller must free().
cnt Receives the element count.
Returns
0 on success, -1 on failure.
Definition at line 334 of file db.c.
References fill_job(), g_db, and JOB_SELECT.
Referenced by handle_jobs_list().
db_job_set_finished()
int db_job_set_finished (int64_t id, const char * status, int exit_code)
Mark a job as finished, recording final status and exit code.
Parameters
id Job row ID.
status "success" or "failed".
exit_code Subprocess exit code.
Returns
0 on success, -1 on failure.
Definition at line 381 of file db.c.
References g_db.
Referenced by runner_thread().
db_job_set_started()
int db_job_set_started (int64_t id)
Mark a job as running and record its start timestamp.
Parameters
id Job row ID.
Returns
0 on success, -1 on failure.
Definition at line 364 of file db.c.
References g_db.
Referenced by runner_thread().
db_open()
int db_open (const char * path)
Open (and schema-initialise) the SQLite3 database.
Parameters
path File-system path for the SQLite database file.
Returns
0 on success, -1 on failure.
Definition at line 115 of file db.c.
References g_db, and SCHEMA.
Referenced by main().
db_session_create()
int db_session_create (const char * token, int64_t user_id, int64_t expires_at)
Insert or replace a session record.
Parameters
token 64-char hex token (primary key).
user_id Owning user ID.
expires_at Unix timestamp of expiry.
Returns
0 on success, -1 on failure.
Definition at line 421 of file db.c.
References g_db.
Referenced by handle_login().
db_session_delete()
int db_session_delete (const char * token)
Delete a session record (logout).
Parameters
token Token to delete.
Returns
0 on success, -1 on failure.
Definition at line 466 of file db.c.
References g_db.
db_session_user()
int db_session_user (const char * token, int64_t now, int64_t * uid_out)
Validate a session token and retrieve the owning user ID.
Parameters
token Token to look up.
now Current Unix timestamp used for expiry check.
uid_out Receives the user_id on success.
Returns
0 if valid and not expired, -1 otherwise.
Definition at line 441 of file db.c.
References g_db.
Referenced by auth_session_user().
db_user_by_id()
int db_user_by_id (int64_t id, User * out)
Look up a user by primary-key ID.
Parameters
id Row ID to search.
out Struct to fill on success.
Returns
0 if found, -1 otherwise.
Definition at line 171 of file db.c.
References fill_user(), and g_db.
Referenced by auth_session_user().
db_user_by_username()
int db_user_by_username (const char * username, User * out)
Look up a user by username.
Parameters
username Login name to search.
out Struct to fill on success.
Returns
0 if found, -1 otherwise.
Definition at line 148 of file db.c.
References fill_user(), and g_db.
Referenced by handle_login(), and seed_admin().
db_user_create()
int db_user_create (const char * username, const char * pwhash, const char * role, int64_t * id_out)
Insert a new user row.
Parameters
username Login name (must be unique).
pwhash Pre-hashed password string ("salt:sha256hex").
role "admin" or "user".
id_out Receives the new row ID; may be NULL.
Returns
0 on success, -1 on failure (e.g. duplicate username).
Definition at line 194 of file db.c.
References g_db.
Referenced by handle_users_create(), and seed_admin().
db_user_delete()
int db_user_delete (int64_t id)
Delete a user by ID.
Parameters
id Row ID to delete.
Returns
0 on success, -1 on failure.
Definition at line 220 of file db.c.
References g_db.
Referenced by handle_user_delete().
db_user_list()
int db_user_list (User ** out, int * cnt)
Fetch all users ordered by ID.
Parameters
out Receives a heap-allocated array; caller must free().
cnt Receives the element count.
Returns
0 on success, -1 on failure.
Definition at line 236 of file db.c.
References fill_user(), and g_db.
Referenced by handle_users_list().