Re-BOOT Web: job.h File Reference
job.h File Reference
Background job runner and Server-Sent Events (SSE) log streamer.
#include <stdint.h>
#include "../mongoose/mongoose.h"
Classes
struct RunningJob
Tracks an in-progress subprocess spawned for a job.
struct SseConn
Tracks a client connection receiving live log output via SSE.
Macros
#define MAX_RUNNING_JOBS 32
#define MAX_SSE_CONNS 64
Functions
int job_run (int64_t job_id, const char *binary, const char *upload_dir, const char *log_dir)
Start a job in a detached background thread.
int job_stop (int64_t job_id)
Send SIGTERM to the subprocess of a running job.
int job_is_running (int64_t job_id)
Check whether a job's subprocess is currently alive.
void job_sse_add (int64_t job_id, struct mg_connection *conn)
Register an SSE connection to stream a job's log output.
void job_sse_poll (void)
Poll all active SSE connections and push any new log lines.
Detailed Description
Background job runner and Server-Sent Events (SSE) log streamer.
Each firmware flash job runs as a detached POSIX thread that fork/exec's the re-boot binary, captures its stdout/stderr into a per-job log file, and updates the database on start and finish. SSE connections registered via job_sse_add() receive new log lines every 300 ms via job_sse_poll().
Author
Subhajit Roy subha.nosp@m.jitr.nosp@m.oy005.nosp@m.@gma.nosp@m.il.co.nosp@m.m
Date
2026-05-06
Definition in file job.h.
Macro Definition Documentation
MAX_RUNNING_JOBS
#define MAX_RUNNING_JOBS 32
Maximum concurrent firmware flash jobs
Definition at line 17 of file job.h.
MAX_SSE_CONNS
#define MAX_SSE_CONNS 64
Maximum concurrent SSE log-tail connections
Definition at line 18 of file job.h.
Function Documentation
job_is_running()
int job_is_running (int64_t job_id)
Check whether a job's subprocess is currently alive.
Parameters
job_id Database job ID.
Returns
1 if running, 0 if not.
Definition at line 285 of file job.c.
References find_job_slot(), and g_lock.
Referenced by handle_job_delete(), and handle_job_run().
job_run()
int job_run (int64_t job_id, const char * binary, const char * upload_dir, const char * log_dir)
Start a job in a detached background thread.
The thread builds the re-boot command line from the job's database record, opens a log file at log_dir/job_ID.log, then fork/exec's the binary. Subprocess stdout and stderr are piped into the log file. The database is updated to "running" on start and "success"/"failed" on finish.
Parameters
job_id Database job ID.
binary Path to the re-boot executable.
upload_dir Directory where uploaded hex files are stored.
log_dir Directory where per-job log files are written.
Returns
0 on success, -1 if the job is already running or thread fails.
Definition at line 240 of file job.c.
References ThreadArg::binary, find_job_slot(), g_lock, ThreadArg::job_id, ThreadArg::log_dir, runner_thread(), and ThreadArg::upload_dir.
Referenced by handle_job_run().
job_sse_add()
void job_sse_add (int64_t job_id, struct mg_connection * conn)
Register an SSE connection to stream a job's log output.
Parameters
job_id Database job ID.
conn Mongoose connection to write SSE events into.
< Maximum concurrent SSE log-tail connections
Definition at line 294 of file job.c.
References SseConn::active, SseConn::conn, g_lock, g_sse, SseConn::job_id, SseConn::log_offset, and MAX_SSE_CONNS.
Referenced by handle_job_stream().
job_sse_poll()
void job_sse_poll (void)
Poll all active SSE connections and push any new log lines.
Called from the Mongoose timer callback (300 ms interval). Tails each job's log file from the last known offset and sends new lines as SSE "data:" frames. Closes connections whose job has finished.
Must be called from the single-threaded Mongoose event loop.
< Maximum concurrent SSE log-tail connections
Definition at line 311 of file job.c.
References SseConn::active, SseConn::conn, g_lock, g_log_dir, g_sse, SseConn::job_id, SseConn::log_offset, and MAX_SSE_CONNS.
Referenced by sse_timer_cb().
job_stop()
int job_stop (int64_t job_id)
Send SIGTERM to the subprocess of a running job.
Parameters
job_id Database job ID.
Returns
0 if the signal was delivered, -1 if the job is not running.
Definition at line 273 of file job.c.
References find_job_slot(), g_lock, and RunningJob::pid.
Referenced by handle_job_stop().