Re-BOOT Web: auth.h File Reference
auth.h File Reference
Password hashing and session-cookie authentication.
#include "db.h"
#include "../mongoose/mongoose.h"
Macros
#define SESSION_TTL 86400
#define TOKEN_LEN 32
#define COOKIE_NAME "rbsid"
Functions
void auth_hash_password (const char *password, char out[128])
Hash a plaintext password with a fresh random salt.
int auth_check_password (const char *password, const char *stored_hash)
Verify a plaintext password against a stored hash.
void auth_gen_token (char out[65])
Generate a cryptographically random 64-char hex session token.
User * auth_session_user (struct mg_http_message *hm)
Extract and validate the session cookie from an HTTP request.
Detailed Description
Password hashing and session-cookie authentication.
Passwords are stored as "salt:sha256hex" where the salt is 8 random bytes encoded as 16 hex characters. Sessions are random 64-char hex tokens persisted in the SQLite session table with a configurable TTL.
Author
Subhajit Roy subha.nosp@m.jitr.nosp@m.oy005.nosp@m.@gma.nosp@m.il.co.nosp@m.m
Date
2026-05-06
Definition in file auth.h.
Macro Definition Documentation
COOKIE_NAME
#define COOKIE_NAME "rbsid"
HTTP cookie name used to carry session tokens
Definition at line 18 of file auth.h.
SESSION_TTL
#define SESSION_TTL 86400
Session lifetime in seconds (24 hours)
Definition at line 16 of file auth.h.
TOKEN_LEN
#define TOKEN_LEN 32
Random bytes consumed per token => 64-char hex
Definition at line 17 of file auth.h.
Function Documentation
auth_check_password()
int auth_check_password (const char * password, const char * stored_hash)
Verify a plaintext password against a stored hash.
Parameters
password Plaintext password to check.
stored_hash Hash string in "salt:sha256hex" format.
Returns
1 if the password matches, 0 otherwise.
< 128-byte string field
Definition at line 61 of file auth.c.
References DB_STR128, and sha256_hex().
Referenced by handle_login().
auth_gen_token()
void auth_gen_token (char out[65])
Generate a cryptographically random 64-char hex session token.
Reads TOKEN_LEN bytes from /dev/urandom.
Parameters
out Output buffer; must be at least 65 bytes.
< Random bytes consumed per token => 64-char hex
Definition at line 90 of file auth.c.
References random_hex(), and TOKEN_LEN.
Referenced by handle_login().
auth_hash_password()
void auth_hash_password (const char * password, char out[128])
Hash a plaintext password with a fresh random salt.
Reads TOKEN_LEN/4 bytes from /dev/urandom to generate the salt, then computes SHA-256("salt:password") and stores the result as "16-char-salt:64-char-sha256hex" in out.
Parameters
password Plaintext password string (NUL-terminated).
out Output buffer; must be at least DB_STR128 bytes.
< 128-byte string field
Definition at line 47 of file auth.c.
References DB_STR128, random_hex(), and sha256_hex().
Referenced by handle_users_create(), and seed_admin().
auth_session_user()
User * auth_session_user (struct mg_http_message * hm)
Extract and validate the session cookie from an HTTP request.
Reads the COOKIE_NAME cookie, validates it against the session table, and returns a heap-allocated User struct on success. The caller is responsible for calling free() on the returned pointer.
Parameters
hm Parsed Mongoose HTTP message.
Returns
Heap-allocated User* on success, NULL if unauthenticated.
< HTTP cookie name used to carry session tokens
Definition at line 150 of file auth.c.
References COOKIE_NAME, db_session_user(), db_user_by_id(), and get_cookie().
Referenced by handle_logout(), and require_auth().