Re-BOOT Web: job.c File Reference
job.c File Reference
Background job runner and SSE log-streaming implementation.
#include "job.h"
#include "db.h"
#include <errno.h>
#include <fcntl.h>
#include <pthread.h>
#include <signal.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/wait.h>
#include <unistd.h>
Classes
struct ThreadArg
Arguments passed to runner_thread() at creation.
Functions
static RunningJob * find_job_slot (int64_t job_id)
Find the active RunningJob slot for job_id.
static RunningJob * alloc_job_slot (void)
Find a free RunningJob slot.
static void * runner_thread (void *arg)
Thread entry point: build command, fork/exec re-boot, stream output.
int job_run (int64_t job_id, const char *binary, const char *upload_dir, const char *log_dir)
Start a job in a detached background thread.
int job_stop (int64_t job_id)
Send SIGTERM to the subprocess of a running job.
int job_is_running (int64_t job_id)
Check whether a job's subprocess is currently alive.
void job_sse_add (int64_t job_id, struct mg_connection *conn)
Register an SSE connection to stream a job's log output.
void job_sse_poll (void)
Poll all active SSE connections and push any new log lines.
Variables
static RunningJob g_jobs [32]
static SseConn g_sse [64]
static pthread_mutex_t g_lock = PTHREAD_MUTEX_INITIALIZER
Detailed Description
Background job runner and SSE log-streaming implementation.
Author
Subhajit Roy subha.nosp@m.jitr.nosp@m.oy005.nosp@m.@gma.nosp@m.il.co.nosp@m.m
Date
2026-05-06
Definition in file job.c.
Function Documentation
alloc_job_slot()
static RunningJob * alloc_job_slot (void) static
Find a free RunningJob slot.
Returns
Pointer to an inactive slot, or NULL if all slots are full.
< Maximum concurrent firmware flash jobs
Definition at line 54 of file job.c.
References g_jobs, and MAX_RUNNING_JOBS.
Referenced by runner_thread().
find_job_slot()
static RunningJob * find_job_slot (int64_t job_id) static
Find the active RunningJob slot for job_id.
Parameters
job_id Database job ID.
Returns
Pointer to the slot, or NULL if not found.
< Maximum concurrent firmware flash jobs
Definition at line 38 of file job.c.
References g_jobs, and MAX_RUNNING_JOBS.
Referenced by job_is_running(), job_run(), job_stop(), and runner_thread().
job_is_running()
int job_is_running (int64_t job_id)
Check whether a job's subprocess is currently alive.
Parameters
job_id Database job ID.
Returns
1 if running, 0 if not.
Definition at line 285 of file job.c.
References find_job_slot(), and g_lock.
Referenced by handle_job_delete(), and handle_job_run().
job_run()
int job_run (int64_t job_id, const char * binary, const char * upload_dir, const char * log_dir)
Start a job in a detached background thread.
The thread builds the re-boot command line from the job's database record, opens a log file at log_dir/job_ID.log, then fork/exec's the binary. Subprocess stdout and stderr are piped into the log file. The database is updated to "running" on start and "success"/"failed" on finish.
Parameters
job_id Database job ID.
binary Path to the re-boot executable.
upload_dir Directory where uploaded hex files are stored.
log_dir Directory where per-job log files are written.
Returns
0 on success, -1 if the job is already running or thread fails.
Definition at line 240 of file job.c.
References ThreadArg::binary, find_job_slot(), g_lock, ThreadArg::job_id, ThreadArg::log_dir, runner_thread(), and ThreadArg::upload_dir.
Referenced by handle_job_run().
job_sse_add()
void job_sse_add (int64_t job_id, struct mg_connection * conn)
Register an SSE connection to stream a job's log output.
Parameters
job_id Database job ID.
conn Mongoose connection to write SSE events into.
< Maximum concurrent SSE log-tail connections
Definition at line 294 of file job.c.
References SseConn::active, SseConn::conn, g_lock, g_sse, SseConn::job_id, SseConn::log_offset, and MAX_SSE_CONNS.
Referenced by handle_job_stream().
job_sse_poll()
void job_sse_poll (void)
Poll all active SSE connections and push any new log lines.
Called from the Mongoose timer callback (300 ms interval). Tails each job's log file from the last known offset and sends new lines as SSE "data:" frames. Closes connections whose job has finished.
Must be called from the single-threaded Mongoose event loop.
< Maximum concurrent SSE log-tail connections
Definition at line 311 of file job.c.
References SseConn::active, SseConn::conn, g_lock, g_log_dir, g_sse, SseConn::job_id, SseConn::log_offset, and MAX_SSE_CONNS.
Referenced by sse_timer_cb().
job_stop()
int job_stop (int64_t job_id)
Send SIGTERM to the subprocess of a running job.
Parameters
job_id Database job ID.
Returns
0 if the signal was delivered, -1 if the job is not running.
Definition at line 273 of file job.c.
References find_job_slot(), g_lock, and RunningJob::pid.
Referenced by handle_job_stop().
runner_thread()
static void * runner_thread (void * arg) static
Thread entry point: build command, fork/exec re-boot, stream output.
Owns the heap-allocated arg and frees it before doing any blocking work. Updates the database on start and finish, and signals SSE connections when the job is complete.
Parameters
arg Heap-allocated ThreadArg; freed inside this function.
Returns
Always NULL.
< 512-byte string field
< Maximum concurrent SSE log-tail connections
Definition at line 91 of file job.c.
References RunningJob::active, SseConn::active, alloc_job_slot(), ThreadArg::binary, db_job_get(), db_job_set_finished(), db_job_set_started(), DB_STR512, Job::device, Job::extra_args, find_job_slot(), g_lock, g_sse, Job::hex_file, Job::interface, RunningJob::job_id, ThreadArg::job_id, ThreadArg::log_dir, MAX_SSE_CONNS, Job::node_id, RunningJob::pid, Job::reset_flag, Job::retries, Job::tcp_port, ThreadArg::upload_dir, and Job::verbose.
Referenced by job_run().
Variable Documentation
g_jobs
RunningJob g_jobs[32] static
Array of all currently active subprocess slots.
Definition at line 21 of file job.c.
Referenced by alloc_job_slot(), and find_job_slot().
g_lock
pthread_mutex_t g_lock = PTHREAD_MUTEX_INITIALIZER static
Mutex protecting both g_jobs[] and g_sse[].
Definition at line 27 of file job.c.
Referenced by job_is_running(), job_run(), job_sse_add(), job_sse_poll(), job_stop(), and runner_thread().
g_sse
SseConn g_sse[64] static
Array of all currently active SSE connection slots.
Definition at line 24 of file job.c.
Referenced by job_sse_add(), job_sse_poll(), and runner_thread().