Re-BOOT Web: main.c File Reference
main.c File Reference
Re-BOOT Web Server entry point.
#include <signal.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/stat.h>
#include "../mongoose/mongoose.h"
#include "auth.h"
#include "db.h"
#include "job.h"
#include "routes.h"
#include "sha256.h"
Functions
static void sig_handler (int sig)
Signal handler for SIGINT and SIGTERM.
static void usage (const char *prog)
Print usage information to stderr.
static void mkdirp (const char *path)
Create a directory if it does not already exist.
static void seed_admin (const char *username, const char *password)
Create the default admin account if no account with username exists.
static void sse_timer_cb (void *arg)
Mongoose timer callback — drives the SSE log-polling loop.
int main (int argc, char *argv[])
Program entry point.
Variables
char g_log_dir [256]
char g_upload_dir [256]
char g_www_dir [256]
char g_binary [256]
static volatile int g_running = 1
Detailed Description
Re-BOOT Web Server entry point.
Parses CLI arguments, initialises the database, creates the default admin account if absent, sets up the Mongoose event loop, and runs the server until a SIGINT or SIGTERM is received.
Author
Subhajit Roy subha.nosp@m.jitr.nosp@m.oy005.nosp@m.@gma.nosp@m.il.co.nosp@m.m
Date
2026-05-06
Definition in file main.c.
Function Documentation
main()
int main (int argc, char * argv[])
Program entry point.
Parameters
argc Argument count.
argv Argument vector.
Returns
0 on clean shutdown, 1 on fatal error.
Definition at line 112 of file main.c.
References db_close(), db_open(), g_binary, g_log_dir, g_running, g_upload_dir, g_www_dir, http_handler(), mkdirp(), seed_admin(), sig_handler(), sse_timer_cb(), and usage().
mkdirp()
static void mkdirp (const char * path) static
Create a directory if it does not already exist.
Parameters
path Directory path to create (mode 0755).
Definition at line 66 of file main.c.
Referenced by main().
seed_admin()
static void seed_admin (const char * username, const char * password) static
Create the default admin account if no account with username exists.
Parameters
username Login name for the admin account.
password Plaintext password for the admin account.
< 128-byte string field
Definition at line 80 of file main.c.
References auth_hash_password(), DB_STR128, db_user_by_username(), and db_user_create().
Referenced by main().
sig_handler()
static void sig_handler (int sig) static
Signal handler for SIGINT and SIGTERM.
Parameters
sig Signal number (unused).
Definition at line 38 of file main.c.
References g_running.
Referenced by main().
sse_timer_cb()
static void sse_timer_cb (void * arg) static
Mongoose timer callback — drives the SSE log-polling loop.
Parameters
arg Unused.
Definition at line 100 of file main.c.
References job_sse_poll().
Referenced by main().
usage()
static void usage (const char * prog) static
Print usage information to stderr.
Parameters
prog argv[0] — the program name.
Definition at line 48 of file main.c.
Referenced by main().
Variable Documentation
g_binary
char g_binary[256] extern
Definition at line 28 of file routes.c.
Referenced by handle_job_run(), and main().
g_log_dir
char g_log_dir[256] extern
Global paths defined in routes.c; modified here from CLI flags.
Runtime-configurable paths — set via CLI flags in main.c.
Definition at line 25 of file routes.c.
Referenced by handle_job_run(), job_sse_poll(), and main().
g_running
volatile int g_running = 1 static
Set to 0 by sig_handler() to break the event loop on shutdown.
Definition at line 32 of file main.c.
Referenced by main(), and sig_handler().
g_upload_dir
char g_upload_dir[256] extern
Definition at line 26 of file routes.c.
Referenced by handle_job_run(), handle_jobs_create(), and main().
g_www_dir
char g_www_dir[256] extern
Definition at line 27 of file routes.c.
Referenced by http_handler(), and main().