Re-BOOT Web: routes.h File Reference
routes.h File Reference
HTTP request dispatcher and REST API handler interface.
#include "../mongoose/mongoose.h"
Functions
void http_handler (struct mg_connection *c, int ev, void *ev_data)
Main Mongoose event handler — register as the HTTP listen callback.
Detailed Description
HTTP request dispatcher and REST API handler interface.
Exposes a single Mongoose event-handler callback that routes incoming HTTP requests to the appropriate handler function and falls back to serving static files from the configured www directory.
Author
Subhajit Roy subha.nosp@m.jitr.nosp@m.oy005.nosp@m.@gma.nosp@m.il.co.nosp@m.m
Date
2026-05-06
Definition in file routes.h.
Function Documentation
http_handler()
void http_handler (struct mg_connection * c, int ev, void * ev_data)
Main Mongoose event handler — register as the HTTP listen callback.
Dispatches MG_EV_HTTP_MSG events to the correct REST endpoint handler based on HTTP method and URI pattern. Unmatched requests are served as static files from the configured www directory.
Parameters
c Active Mongoose connection.
ev Mongoose event type.
ev_data Event-specific data (cast to mg_http_message* for HTTP).
Definition at line 761 of file routes.c.
References g_www_dir, handle_job_delete(), handle_job_get(), handle_job_run(), handle_job_status(), handle_job_stop(), handle_job_stream(), handle_jobs_create(), handle_jobs_list(), handle_login(), handle_logout(), handle_me(), handle_user_delete(), handle_users_create(), handle_users_list(), has_suffix(), IS, match_prefix(), METH, parse_id(), reply_err(), and URI.
Referenced by main().