Re-BOOT Web: routes.c File Reference
routes.c File Reference
HTTP request dispatcher and REST API handler implementation.
#include "routes.h"
#include "auth.h"
#include "db.h"
#include "job.h"
#include <fcntl.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/stat.h>
#include <time.h>
#include <unistd.h>
Macros
#define JSTR(f) ({ static char _b[512]; json_esc(f, _b, sizeof(_b)); _b; })
#define GETFIELD(field)
#define METH(m) (mg_strcmp(hm->method, mg_str(m)) == 0)
#define URI(p) (mg_match(hm->uri, mg_str(p), NULL))
#define IS(m, p) (METH(m) && URI(p))
Functions
static void json_esc (const char *src, char *dst, size_t dlen)
Escape a string for safe embedding as a JSON string value.
static void reply_json (struct mg_connection *c, int status, const char *body)
Send a JSON response with the given HTTP status code.
static void reply_err (struct mg_connection *c, int status, const char *msg)
Send a JSON error response: {"error":"<msg>"}.
static User * require_auth (struct mg_connection *c, struct mg_http_message *hm)
Validate session cookie; send 401 and return NULL on failure.
static void handle_login (struct mg_connection *c, struct mg_http_message *hm)
POST /api/login — authenticate and set session cookie.
static void handle_logout (struct mg_connection *c, struct mg_http_message *hm)
POST /api/logout — expire the session cookie.
static void handle_me (struct mg_connection *c, struct mg_http_message *hm)
GET /api/me — return the authenticated user's profile.
static void job_to_json (const Job *j, char *buf, size_t blen)
Serialise a Job struct into a JSON object string.
static void handle_jobs_list (struct mg_connection *c, struct mg_http_message *hm)
GET /api/jobs — return a JSON array of all jobs.
static void handle_jobs_create (struct mg_connection *c, struct mg_http_message *hm)
POST /api/jobs — create a job from a multipart form upload.
static void handle_job_get (struct mg_connection *c, struct mg_http_message *hm, int64_t job_id)
GET /api/jobs/:id — return a single job as JSON.
static void handle_job_run (struct mg_connection *c, struct mg_http_message *hm, int64_t job_id)
POST /api/jobs/:id/run — start the re-boot subprocess for a job.
static void handle_job_stop (struct mg_connection *c, struct mg_http_message *hm, int64_t job_id)
POST /api/jobs/:id/stop — send SIGTERM to the running subprocess.
static void handle_job_delete (struct mg_connection *c, struct mg_http_message *hm, int64_t job_id)
DELETE /api/jobs/:id — remove a job that is not currently running.
static void handle_job_status (struct mg_connection *c, struct mg_http_message *hm, int64_t job_id)
GET /api/jobs/:id/status — return job status and exit code as JSON.
static void handle_job_stream (struct mg_connection *c, struct mg_http_message *hm, int64_t job_id)
GET /api/jobs/:id/stream — upgrade to an SSE log-streaming response.
static void handle_users_list (struct mg_connection *c, struct mg_http_message *hm)
GET /api/users — list all users (admin only).
static void handle_users_create (struct mg_connection *c, struct mg_http_message *hm)
POST /api/users — create a new user account (admin only).
static void handle_user_delete (struct mg_connection *c, struct mg_http_message *hm, int64_t uid)
DELETE /api/users/:id — remove a user account (admin only).
static int match_prefix (struct mg_str uri, const char *prefix)
Return 1 if uri starts with prefix.
static int64_t parse_id (struct mg_str uri, const char *prefix)
Extract the integer ID that immediately follows prefix in uri.
static int has_suffix (struct mg_str uri, const char *prefix, const char *suffix)
Return 1 if the path segment after the numeric ID matches suffix.
void http_handler (struct mg_connection *c, int ev, void *ev_data)
Main Mongoose event handler — register as the HTTP listen callback.
Variables
char g_log_dir [256] = "logs"
char g_upload_dir [256] = "uploads"
char g_www_dir [256] = "www"
char g_binary [256] = "./re-boot"
Detailed Description
HTTP request dispatcher and REST API handler implementation.
Implements the complete REST API surface: authentication, job management, user management, and SSE log streaming. Static files are served by Mongoose's built-in directory handler.
Author
Subhajit Roy subha.nosp@m.jitr.nosp@m.oy005.nosp@m.@gma.nosp@m.il.co.nosp@m.m
Date
2026-05-06
Definition in file routes.c.
Macro Definition Documentation
GETFIELD
#define GETFIELD (field)
Value:
        if (strcmp(fname, #field) == 0) \
        { \
            size_t l = part.body.len < sizeof(j.field) - 1 \
                     ? part.body.len : sizeof(j.field) - 1; \
            memcpy(j.field, part.body.buf, l); \
            j.field[l] = '\0'; \
        }
IS
#define IS (m, p) (METH(m) && URI(p))
Test both method and URI.
Definition at line 759 of file routes.c.
JSTR
#define JSTR (f) ({ static char _b[512]; json_esc(f, _b, sizeof(_b)); _b; })
Escape f into a static buffer and return a pointer to that buffer.
Definition at line 79 of file routes.c.
METH
#define METH (m) (mg_strcmp(hm->method, mg_str(m)) == 0)
Test HTTP method against a string literal.
Definition at line 755 of file routes.c.
URI
#define URI (p) (mg_match(hm->uri, mg_str(p), NULL))
Test URI against a glob pattern.
Definition at line 757 of file routes.c.
Function Documentation
handle_job_delete()
static void handle_job_delete (struct mg_connection * c, struct mg_http_message * hm, int64_t job_id) static
DELETE /api/jobs/:id — remove a job that is not currently running.
Definition at line 489 of file routes.c.
References db_job_delete(), job_is_running(), reply_err(), reply_json(), and require_auth().
Referenced by http_handler().
handle_job_get()
static void handle_job_get (struct mg_connection * c, struct mg_http_message * hm, int64_t job_id) static
GET /api/jobs/:id — return a single job as JSON.
Definition at line 420 of file routes.c.
References db_job_get(), job_to_json(), reply_err(), reply_json(), and require_auth().
Referenced by http_handler().
handle_job_run()
static void handle_job_run (struct mg_connection * c, struct mg_http_message * hm, int64_t job_id) static
POST /api/jobs/:id/run — start the re-boot subprocess for a job.
Definition at line 445 of file routes.c.
References g_binary, g_log_dir, g_upload_dir, job_is_running(), job_run(), reply_err(), reply_json(), and require_auth().
Referenced by http_handler().
handle_job_status()
static void handle_job_status (struct mg_connection * c, struct mg_http_message * hm, int64_t job_id) static
GET /api/jobs/:id/status — return job status and exit code as JSON.
Definition at line 512 of file routes.c.
References db_job_get(), Job::exit_code, reply_err(), reply_json(), require_auth(), and Job::status.
Referenced by http_handler().
handle_job_stop()
static void handle_job_stop (struct mg_connection * c, struct mg_http_message * hm, int64_t job_id) static
POST /api/jobs/:id/stop — send SIGTERM to the running subprocess.
Definition at line 472 of file routes.c.
References job_stop(), reply_json(), and require_auth().
Referenced by http_handler().
handle_job_stream()
static void handle_job_stream (struct mg_connection * c, struct mg_http_message * hm, int64_t job_id) static
GET /api/jobs/:id/stream — upgrade to an SSE log-streaming response.
Sends the SSE headers and registers the connection with job_sse_add(). The Mongoose timer will push log lines via job_sse_poll() every 300 ms.
Definition at line 541 of file routes.c.
References job_sse_add(), and require_auth().
Referenced by http_handler().
handle_jobs_create()
static void handle_jobs_create (struct mg_connection * c, struct mg_http_message * hm) static
POST /api/jobs — create a job from a multipart form upload.
The hex_file field must be a file upload. All other fields are optional text parts. The uploaded file is saved with a Unix-timestamp prefix to avoid name collisions between concurrent uploads.
Definition at line 300 of file routes.c.
References db_job_create(), Job::device, g_upload_dir, GETFIELD, Job::hex_file, User::id, Job::name, Job::node_id, reply_err(), reply_json(), require_auth(), and Job::user_id.
Referenced by http_handler().
handle_jobs_list()
static void handle_jobs_list (struct mg_connection * c, struct mg_http_message * hm) static
GET /api/jobs — return a JSON array of all jobs.
Definition at line 257 of file routes.c.
References db_job_list(), job_to_json(), reply_json(), and require_auth().
Referenced by http_handler().
handle_login()
static void handle_login (struct mg_connection * c, struct mg_http_message * hm) static
POST /api/login — authenticate and set session cookie.
Accepts both application/x-www-form-urlencoded and JSON bodies.
< Session lifetime in seconds (24 hours)
< HTTP cookie name used to carry session tokens
Definition at line 140 of file routes.c.
References auth_check_password(), auth_gen_token(), COOKIE_NAME, db_session_create(), db_user_by_username(), User::id, JSTR, User::pwhash, reply_err(), User::role, SESSION_TTL, and User::username.
Referenced by http_handler().
handle_logout()
static void handle_logout (struct mg_connection * c, struct mg_http_message * hm) static
POST /api/logout — expire the session cookie.
< HTTP cookie name used to carry session tokens
Definition at line 192 of file routes.c.
References auth_session_user(), and COOKIE_NAME.
Referenced by http_handler().
handle_me()
static void handle_me (struct mg_connection * c, struct mg_http_message * hm) static
GET /api/me — return the authenticated user's profile.
Definition at line 210 of file routes.c.
References User::id, JSTR, reply_json(), require_auth(), User::role, and User::username.
Referenced by http_handler().
handle_user_delete()
static void handle_user_delete (struct mg_connection * c, struct mg_http_message * hm, int64_t uid) static
DELETE /api/users/:id — remove a user account (admin only).
An admin cannot delete their own account.
Definition at line 677 of file routes.c.
References db_user_delete(), User::id, reply_err(), reply_json(), require_auth(), and User::role.
Referenced by http_handler().
handle_users_create()
static void handle_users_create (struct mg_connection * c, struct mg_http_message * hm) static
POST /api/users — create a new user account (admin only).
Expects a JSON body with "username", "password", and optional "role".
< 128-byte string field
Definition at line 615 of file routes.c.
References auth_hash_password(), DB_STR128, db_user_create(), reply_err(), reply_json(), require_auth(), and User::role.
Referenced by http_handler().
handle_users_list()
static void handle_users_list (struct mg_connection * c, struct mg_http_message * hm) static
GET /api/users — list all users (admin only).
Definition at line 567 of file routes.c.
References db_user_list(), JSTR, reply_err(), reply_json(), require_auth(), and User::role.
Referenced by http_handler().
has_suffix()
static int has_suffix (struct mg_str uri, const char * prefix, const char * suffix) static
Return 1 if the path segment after the numeric ID matches suffix.
Parameters
uri Full request URI.
prefix URI prefix before the numeric ID (e.g. "/api/jobs/").
suffix Expected suffix after the ID (e.g. "/run").
Definition at line 730 of file routes.c.
Referenced by http_handler().
http_handler()
void http_handler (struct mg_connection * c, int ev, void * ev_data)
Main Mongoose event handler — register as the HTTP listen callback.
Dispatches MG_EV_HTTP_MSG events to the correct REST endpoint handler based on HTTP method and URI pattern. Unmatched requests are served as static files from the configured www directory.
Parameters
c Active Mongoose connection.
ev Mongoose event type.
ev_data Event-specific data (cast to mg_http_message* for HTTP).
Definition at line 761 of file routes.c.
References g_www_dir, handle_job_delete(), handle_job_get(), handle_job_run(), handle_job_status(), handle_job_stop(), handle_job_stream(), handle_jobs_create(), handle_jobs_list(), handle_login(), handle_logout(), handle_me(), handle_user_delete(), handle_users_create(), handle_users_list(), has_suffix(), IS, match_prefix(), METH, parse_id(), reply_err(), and URI.
Referenced by main().
job_to_json()
static void job_to_json (const Job * j, char * buf, size_t blen) static
Serialise a Job struct into a JSON object string.
Parameters
j Source job.
buf Output buffer.
blen Size of buf in bytes.
Definition at line 235 of file routes.c.
References Job::created_at, Job::device, Job::exit_code, Job::extra_args, Job::finished_at, Job::hex_file, Job::id, Job::interface, JSTR, Job::name, Job::node_id, Job::reset_flag, Job::retries, Job::started_at, Job::status, Job::tcp_port, Job::user_id, Job::username, and Job::verbose.
Referenced by handle_job_get(), and handle_jobs_list().
json_esc()
static void json_esc (const char * src, char * dst, size_t dlen) static
Escape a string for safe embedding as a JSON string value.
Handles backslash, double-quote, and common control characters.
Parameters
src Source string (NUL-terminated).
dst Destination buffer.
dlen Size of dst in bytes.
Definition at line 43 of file routes.c.
match_prefix()
static int match_prefix (struct mg_str uri, const char * prefix) static
Return 1 if uri starts with prefix.
Definition at line 704 of file routes.c.
Referenced by http_handler().
parse_id()
static int64_t parse_id (struct mg_str uri, const char * prefix) static
Extract the integer ID that immediately follows prefix in uri.
Returns
Parsed ID, or -1 if the URI is too short.
Definition at line 714 of file routes.c.
Referenced by http_handler().
reply_err()
static void reply_err (struct mg_connection * c, int status, const char * msg) static
Send a JSON error response: {"error":"<msg>"}.
Parameters
c Mongoose connection.
status HTTP status code.
msg Error message string.
Definition at line 101 of file routes.c.
References reply_json().
Referenced by handle_job_delete(), handle_job_get(), handle_job_run(), handle_job_status(), handle_jobs_create(), handle_login(), handle_user_delete(), handle_users_create(), handle_users_list(), http_handler(), and require_auth().
reply_json()
static void reply_json (struct mg_connection * c, int status, const char * body) static
Send a JSON response with the given HTTP status code.
Parameters
c Mongoose connection.
status HTTP status code.
body NUL-terminated JSON body string.
Definition at line 87 of file routes.c.
Referenced by handle_job_delete(), handle_job_get(), handle_job_run(), handle_job_status(), handle_job_stop(), handle_jobs_create(), handle_jobs_list(), handle_me(), handle_user_delete(), handle_users_create(), handle_users_list(), and reply_err().
require_auth()
static User * require_auth (struct mg_connection * c, struct mg_http_message * hm) static
Validate session cookie; send 401 and return NULL on failure.
Returns a heap-allocated User on success. The caller must free() it.
Parameters
c Mongoose connection used to send the 401 response.
hm Parsed HTTP message.
Returns
Heap-allocated User* or NULL.
Definition at line 121 of file routes.c.
References auth_session_user(), and reply_err().
Referenced by handle_job_delete(), handle_job_get(), handle_job_run(), handle_job_status(), handle_job_stop(), handle_job_stream(), handle_jobs_create(), handle_jobs_list(), handle_me(), handle_user_delete(), handle_users_create(), and handle_users_list().
Variable Documentation
g_binary
char g_binary[256] = "./re-boot"
Definition at line 28 of file routes.c.
Referenced by handle_job_run(), and main().
g_log_dir
char g_log_dir[256] = "logs"
Runtime-configurable paths — set via CLI flags in main.c.
Definition at line 25 of file routes.c.
Referenced by handle_job_run(), job_sse_poll(), and main().
g_upload_dir
char g_upload_dir[256] = "uploads"
Definition at line 26 of file routes.c.
Referenced by handle_job_run(), handle_jobs_create(), and main().
g_www_dir
char g_www_dir[256] = "www"
Definition at line 27 of file routes.c.
Referenced by http_handler(), and main().