Re-BOOT Web: sha256.c File Reference
sha256.c File Reference
SHA-256 hash algorithm implementation.
#include "sha256.h"
#include <string.h>
Macros
#define ROTRIGHT(a, b) (((a) >> (b)) | ((a) << (32 - (b))))
#define CH(x, y, z) (((x) & (y)) ^ (~(x) & (z)))
#define MAJ(x, y, z) (((x) & (y)) ^ ((x) & (z)) ^ ((y) & (z)))
#define EP0(x) (ROTRIGHT(x, 2) ^ ROTRIGHT(x, 13) ^ ROTRIGHT(x, 22))
#define EP1(x) (ROTRIGHT(x, 6) ^ ROTRIGHT(x, 11) ^ ROTRIGHT(x, 25))
#define SIG0(x) (ROTRIGHT(x, 7) ^ ROTRIGHT(x, 18) ^ ((x) >> 3))
#define SIG1(x) (ROTRIGHT(x, 17) ^ ROTRIGHT(x, 19) ^ ((x) >> 10))
Functions
static void sha256_transform (SHA256_CTX *ctx, const uint8_t data[])
Process one 512-bit block and update the running hash state.
void sha256_init (SHA256_CTX *ctx)
Initialise a SHA-256 context with the standard IV.
void sha256_update (SHA256_CTX *ctx, const uint8_t *data, size_t len)
Feed bytes into an ongoing SHA-256 computation.
void sha256_final (SHA256_CTX *ctx, uint8_t hash[32])
Finalise the digest and write 32 raw bytes to hash.
void sha256_hex (const uint8_t *data, size_t len, char out[65])
Compute SHA-256 of data and write it as a 64-char lowercase hex string (plus NUL terminator).
Variables
static const uint32_t K [64]
Detailed Description
SHA-256 hash algorithm implementation.
Public-domain implementation originally by Brad Conte. Source: https://github.com/B-Con/crypto-algorithms
Author
Subhajit Roy subha.nosp@m.jitr.nosp@m.oy005.nosp@m.@gma.nosp@m.il.co.nosp@m.m
Date
2026-05-06
Definition in file sha256.c.
Macro Definition Documentation
CH
#define CH (x, y, z) (((x) & (y)) ^ (~(x) & (z)))
Definition at line 15 of file sha256.c.
EP0
#define EP0 (x) (ROTRIGHT(x, 2) ^ ROTRIGHT(x, 13) ^ ROTRIGHT(x, 22))
Definition at line 17 of file sha256.c.
EP1
#define EP1 (x) (ROTRIGHT(x, 6) ^ ROTRIGHT(x, 11) ^ ROTRIGHT(x, 25))
Definition at line 18 of file sha256.c.
MAJ
#define MAJ (x, y, z) (((x) & (y)) ^ ((x) & (z)) ^ ((y) & (z)))
Definition at line 16 of file sha256.c.
ROTRIGHT
#define ROTRIGHT (a, b) (((a) >> (b)) | ((a) << (32 - (b))))
Definition at line 14 of file sha256.c.
SIG0
#define SIG0 (x) (ROTRIGHT(x, 7) ^ ROTRIGHT(x, 18) ^ ((x) >> 3))
Definition at line 19 of file sha256.c.
SIG1
#define SIG1 (x) (ROTRIGHT(x, 17) ^ ROTRIGHT(x, 19) ^ ((x) >> 10))
Definition at line 20 of file sha256.c.
Function Documentation
sha256_final()
void sha256_final (SHA256_CTX * ctx, uint8_t hash[32])
Finalise the digest and write 32 raw bytes to hash.
Parameters
ctx Context with accumulated data.
hash Output buffer; must be at least 32 bytes.
Definition at line 112 of file sha256.c.
References SHA256_CTX::bitlen, SHA256_CTX::data, SHA256_CTX::datalen, sha256_transform(), and SHA256_CTX::state.
Referenced by sha256_hex().
sha256_hex()
void sha256_hex (const uint8_t * data, size_t len, char out[65])
Compute SHA-256 of data and write it as a 64-char lowercase hex string (plus NUL terminator).
Parameters
data Input bytes.
len Number of input bytes.
out Output buffer; must be at least 65 bytes.
Definition at line 159 of file sha256.c.
References sha256_final(), sha256_init(), and sha256_update().
Referenced by auth_check_password(), and auth_hash_password().
sha256_init()
void sha256_init (SHA256_CTX * ctx)
Initialise a SHA-256 context with the standard IV.
Parameters
ctx Context to initialise.
Definition at line 83 of file sha256.c.
References SHA256_CTX::bitlen, SHA256_CTX::datalen, and SHA256_CTX::state.
Referenced by sha256_hex().
sha256_transform()
static void sha256_transform (SHA256_CTX * ctx, const uint8_t data[]) static
Process one 512-bit block and update the running hash state.
Parameters
ctx Context carrying the current hash state.
data Pointer to exactly 64 bytes of input.
Definition at line 48 of file sha256.c.
References CH, EP0, EP1, K, MAJ, SIG0, SIG1, and SHA256_CTX::state.
Referenced by sha256_final(), and sha256_update().
sha256_update()
void sha256_update (SHA256_CTX * ctx, const uint8_t * data, size_t len)
Feed bytes into an ongoing SHA-256 computation.
Parameters
ctx Context previously initialised with sha256_init().
data Pointer to input bytes.
len Number of bytes to process.
Definition at line 97 of file sha256.c.
References SHA256_CTX::bitlen, SHA256_CTX::data, SHA256_CTX::datalen, and sha256_transform().
Referenced by sha256_hex().
Variable Documentation
K
const uint32_t K[64] static
Initial value:
=
{
    0x428a2f98, 0x71374491, 0xb5c0fbcf, 0xe9b5dba5,
    0x3956c25b, 0x59f111f1, 0x923f82a4, 0xab1c5ed5,
    0xd807aa98, 0x12835b01, 0x243185be, 0x550c7dc3,
    0x72be5d74, 0x80deb1fe, 0x9bdc06a7, 0xc19bf174,
    0xe49b69c1, 0xefbe4786, 0x0fc19dc6, 0x240ca1cc,
    0x2de92c6f, 0x4a7484aa, 0x5cb0a9dc, 0x76f988da,
    0x983e5152, 0xa831c66d, 0xb00327c8, 0xbf597fc7,
    0xc6e00bf3, 0xd5a79147, 0x06ca6351, 0x14292967,
    0x27b70a85, 0x2e1b2138, 0x4d2c6dfc, 0x53380d13,
    0x650a7354, 0x766a0abb, 0x81c2c92e, 0x92722c85,
    0xa2bfe8a1, 0xa81a664b, 0xc24b8b70, 0xc76c51a3,
    0xd192e819, 0xd6990624, 0xf40e3585, 0x106aa070,
    0x19a4c116, 0x1e376c08, 0x2748774c, 0x34b0bcb5,
    0x391c0cb3, 0x4ed8aa4a, 0x5b9cca4f, 0x682e6ff3,
    0x748f82ee, 0x78a5636f, 0x84c87814, 0x8cc70208,
    0x90befffa, 0xa4506ceb, 0xbef9a3f7, 0xc67178f2
}
SHA-256 round constants (first 32 bits of cube roots of primes 2..311).
Definition at line 23 of file sha256.c.
Referenced by sha256_transform().