Re-BOOT Web: sha256.h File Reference
sha256.h File Reference
SHA-256 hash algorithm interface.
#include <stddef.h>
#include <stdint.h>
Classes
struct SHA256_CTX
SHA-256 computation context.
Functions
void sha256_init (SHA256_CTX *ctx)
Initialise a SHA-256 context with the standard IV.
void sha256_update (SHA256_CTX *ctx, const uint8_t *data, size_t len)
Feed bytes into an ongoing SHA-256 computation.
void sha256_final (SHA256_CTX *ctx, uint8_t hash[32])
Finalise the digest and write 32 raw bytes to hash.
void sha256_hex (const uint8_t *data, size_t len, char out[65])
Compute SHA-256 of data and write it as a 64-char lowercase hex string (plus NUL terminator).
Detailed Description
SHA-256 hash algorithm interface.
Public-domain SHA-256 implementation originally by Brad Conte. Source: https://github.com/B-Con/crypto-algorithms
Author
Subhajit Roy subha.nosp@m.jitr.nosp@m.oy005.nosp@m.@gma.nosp@m.il.co.nosp@m.m
Date
2026-05-06
Definition in file sha256.h.
Function Documentation
sha256_final()
void sha256_final (SHA256_CTX * ctx, uint8_t hash[32])
Finalise the digest and write 32 raw bytes to hash.
Parameters
ctx Context with accumulated data.
hash Output buffer; must be at least 32 bytes.
Definition at line 112 of file sha256.c.
References SHA256_CTX::bitlen, SHA256_CTX::data, SHA256_CTX::datalen, sha256_transform(), and SHA256_CTX::state.
Referenced by sha256_hex().
sha256_hex()
void sha256_hex (const uint8_t * data, size_t len, char out[65])
Compute SHA-256 of data and write it as a 64-char lowercase hex string (plus NUL terminator).
Parameters
data Input bytes.
len Number of input bytes.
out Output buffer; must be at least 65 bytes.
Definition at line 159 of file sha256.c.
References sha256_final(), sha256_init(), and sha256_update().
Referenced by auth_check_password(), and auth_hash_password().
sha256_init()
void sha256_init (SHA256_CTX * ctx)
Initialise a SHA-256 context with the standard IV.
Parameters
ctx Context to initialise.
Definition at line 83 of file sha256.c.
References SHA256_CTX::bitlen, SHA256_CTX::datalen, and SHA256_CTX::state.
Referenced by sha256_hex().
sha256_update()
void sha256_update (SHA256_CTX * ctx, const uint8_t * data, size_t len)
Feed bytes into an ongoing SHA-256 computation.
Parameters
ctx Context previously initialised with sha256_init().
data Pointer to input bytes.
len Number of bytes to process.
Definition at line 97 of file sha256.c.
References SHA256_CTX::bitlen, SHA256_CTX::data, SHA256_CTX::datalen, and sha256_transform().
Referenced by sha256_hex().